apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storageclass-gp3
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  source:
    repoURL: https://github.com/emmauopeople/k8s-microservice-cms.git
    targetRevision: main
    path: k8s/platform/storage
